#!/bin/bash

#[[ -z "$1" ]] && echo "Usage: $0 <CID>" && exit 1

for i in $(seq 1 20)
  do n=$(printf "%03d" $i)
   docker run -d -h rundeck_client_$i.foo.bar --name="rundeck_client_$i" -P --dns 172.17.0.2 rundeckclient
 done
